from django.urls import path
from . import views

from .views import (
    ScrapeProductsPageView,
    get_processing_progress,
    stop_processing,
    task_progress,
    stop_task,
    find_zero_skus,
    list_all_urls,
)
from .views import json_to_csv

# app_name = 'machine'
urlpatterns = [
    # path("sysco_api/", SyscoApiPageView.as_view(), name="sysco_api"),

    path('all-urls/', list_all_urls, name='all_urls'),
    path('application/', views.application, name='application'),
    # BigCommerce
    path('meats_linz/', views.scrape_meats_linz, name='meats_linz'),
    path('terra_spice/', views.scrape_terra_spice, name='terra_spice'),
    # Misc
    path('imperial_dade/', views.scrape_imperial_dade, name='imperial_dade'),
    path("breakthru/", views.scrape_breakthru, name="breakthru"),
    path("hive_template/", views.scrape_hive_template, name="hive_template"),
    path("archer_liquor/", views.scrape_archer_liquor, name="archer_liquor"),
    path("empire_metro/", views.scrape_empire_metro, name="empire_metro"),
    path("empire_north/", views.scrape_empire_north, name="empire_north"),
    path("maverick_beverage/", views.scrape_maverick_beverage, name="maverick_beverage"),
    path("morrell_wine/", views.scrape_morrell_wine, name="morrell_wine"),
    path("twin_liquors/", views.scrape_twin_liquors, name="twin_liquors"),
    path("cellar_53/", views.scrape_cellar_53, name="cellar_53"),
    path("sandr_liquors/", views.scrape_sandr_liquors, name="sandr_liquors"),
    path("south_hills_wine/", views.scrape_south_hills_wine, name="south_hills_wine"),
    path("wine-wine_searcher/", views.scrape_wine_searcher, name="wine_searcher"),
    path("sysco/", views.scrape_sysco, name="sysco"),
    path("webstaurant/", views.scrape_webstaurant, name="webstaurant"),
    path("sg/", views.scrape_sg, name="sg"),
    path("usfoods/", views.scrape_usfoods, name="usfoods"),
    path("ab/", views.scrape_ab, name="ab"),
    path("acc_distributors/", views.scrape_acc_distributors, name="acc_distributors"),
    path("acme_steak/", views.scrape_acme_steak, name="acme_steak"),
    path("all_fresh_seafood/", views.scrape_all_fresh_seafood, name="all_fresh_seafood"),
    path("display_sample_data/", views.display_sample_data, name="display_sample_data"),
    path("all_star_specialties/", views.scrape_all_star_specialties, name="all_star_specialties"),
    path("dicarlo/", views.scrape_dicarlo, name="dicarlo"),
    path("alpeake/", views.scrape_alpeake, name="alpeake"),
    path("api/stop_processing/", stop_processing, name="stop_processing"),
    path("apito/", views.scrape_apito, name="apito"),
    path("birite/", views.scrape_birite, name="birite"),
    path("carmela/", views.scrape_carmela, name="carmela"),
    path("caruso/", views.scrape_caruso, name="caruso"),
    path("cheese_importers/", views.scrape_cheese_importers, name="cheese_importers"),
    path("chefs_kitchen/", views.scrape_chefs_kitchen, name="chefs_kitchen"),
    path("cheney_brothers/", views.scrape_cheney_brothers, name="cheney_brothers"),
    path("citylinefoods/", views.scrape_citylinefoods, name="citylinefoods"),
    path("christ_panos/", views.scrape_christ_panos, name="christ_panos"),
    path("cooks_company/", views.scrape_cooks_company, name="cooks_company"),
    path("creamco/", views.scrape_creamco, name="creamco"),
    path("crookbros/", views.scrape_crookbros, name="crookbros"),
    path("cusumanoandsons/", views.scrape_cusumanoandsons, name="cusumanoandsons"),
    path("cw/", views.scrape_cw, name="cw"),
    path("derstines/", views.scrape_derstines, name="derstines"),
    path("driscoll/", views.scrape_driscoll, name="driscoll"),
    path("dwcspecialties/", views.scrape_dwcspecialties, name="dwcspecialties"),
    path("foodandpaper/", views.scrape_foodandpaper, name="foodandpaper"),
    path("foodpro/", views.scrape_foodpro, name="foodpro"),
    path("fourstarmeat/", views.scrape_fourstarmeat, name="fourstarmeat"),
    path("get_processing_progress/", get_processing_progress, name="get_processing_progress"),
    path("hooktofork/", views.scrape_hooktofork, name="hooktofork"),
    path("indianhead/", views.scrape_indianhead, name="indianhead"),
    path("jordanpaige/", views.scrape_jordanpaige, name="jordanpaige"),
    path("manson/", views.scrape_manson, name="manson"),
    path("maple_vale/", views.scrape_maple_vale, name="maple_vale"),
    path("market_406/", views.scrape_market_406, name="market_406"),
    path("misterproduce/", views.scrape_misterproduce, name="misterproduce"),
    path("pacificprovisions/", views.scrape_pacificprovisions, name="pacificprovisions"),
    path("prdeli/", views.scrape_prdeli, name="prdeli"),
    path("primesourcefoods/", views.scrape_primesourcefoods, name="primesourcefoods"),
    path("rarefoods/", views.scrape_rarefoods, name="rarefoods"),
    path("realityfoods/", views.scrape_realityfoods, name="realityfoods"),
    path("safradistribution/", views.scrape_safradistribution, name="safradistribution"),
    path("savalfoodservice/", views.scrape_savalfoodservice, name="savalfoodservice"),
    path("scrape_products/", ScrapeProductsPageView.as_view(), name="scrape_products"),
    path("scrapers/count-csv-rows/", views.count_csv_rows, name="count_csv_rows"),
    path("scrapers/search-requests/", views.search_requests, name="search_requests"),
    path("scrapers/update-distributor/", views.update_distributor, name="update_distributor"),
    path("sierra_meat/", views.scrape_sierra_meat, name="sierra_meat"),
    path("socomeatco/", views.scrape_socomeatco, name="socomeatco"),
    path("southwest_traders/", views.scrape_southwest_traders, name="southwest_traders"),
    path("sunbelt/", views.scrape_sunbelt, name="sunbelt"),
    path("sutters/", views.scrape_sutters, name="sutters"),
    path("thefishguys/", views.scrape_thefishguys, name="thefishguys"),
    path("tolteca/", views.scrape_tolteca, name="tolteca"),
    path("totalfoods/", views.scrape_totalfoods, name="totalfoods"),
    path("alma/", views.scrape_alma, name="alma"),
    path("allen_brothers/", views.scrape_allen_brothers, name="allen_brothers"),
    path("fulton_fish/", views.scrape_fulton_fish, name="fulton_fish"),
    path("melissas/", views.scrape_melissas, name="melissas"),
    path("bitters_bottles/", views.scrape_bitters_bottles, name="bitters_bottles"),
    path("savory_gourmet/", views.scrape_savory_gourmet, name="savory_gourmet"),
    path("pacific_gourmet/", views.scrape_pacific_gourmet, name="pacific_gourmet"),
    path("four_star_seafood/", views.scrape_four_star_seafood, name="four_star_seafood"),
    path("valleygold/", views.scrape_valleygold, name="valleygold"),
    path("vitco_foods/", views.scrape_vitco_foods, name="vitco_foods"),
    path("wagner/", views.scrape_wagner, name="wagner"),
    path("whatchefswant-south/", views.scrape_whatchefswant_south, name="whatchefswant_south"),
    path("whatchefswant_central/", views.scrape_whatchefswant_central, name="whatchefswant_central"),
    path("whatchefswant_rockies/", views.scrape_whatchefswant_rockies, name="whatchefswant_rockies"),
    path("woolcofoods/", views.scrape_woolcofoods, name="woolcofoods"),
    path("hearty/", views.scrape_hearty, name="hearty"),
    path("primizie_ny/", views.scrape_primizie_ny, name="primizie_ny"),
    path("primizie_noca/", views.scrape_primizie_noca, name="primizie_noca"),
    path("sandw/", views.scrape_sandw, name="sandw"),
    path("sardilli/", views.scrape_sardilli, name="sardilli"),
    path("status/", views.scraper_status, name="scraper_status"),
    path('task-status/', views.task_status, name='task_status'),
    path('stop-task/<str:task_id>/', views.stop_task, name='stop_task'),
    path('unipro/', views.scrape_unipro, name='unipro'),
    # Task progress and control endpoints
    path('api/task-progress/<str:task_id>/', task_progress, name='api_task_progress'),
    path('api/stop-task/<str:task_id>/', stop_task, name='api_stop_task'),

    path('json-to-csv/', json_to_csv, name='json_to_csv'),

    path('find-zero-skus/', find_zero_skus, name='find_zero_skus'),

    path("ace_endico/", views.scrape_ace_endico, name="ace_endico"),
    path("brothers_food/", views.scrape_brothers_food, name="brothers_food"),
    path("city_produce/", views.scrape_city_produce, name="city_produce"),
    path("cibo/", views.scrape_cibo, name="cibo"),
    path("graves_foods/", views.scrape_graves_foods, name="graves_foods"),
    path("kuno/", views.scrape_kuno, name="kuno"),
    path("piazza/", views.scrape_piazza, name="piazza"),

    path("prime_source/", views.scrape_prime_source, name="prime_source"),
    path("sirna_sons/", views.scrape_sirna_sons, name="sirna_sons"),
    path("dennis_foodservice/", views.scrape_dennis_foodservice, name="dennis_foodservice"),
    path("earthly_gourmet/", views.scrape_earthly_gourmet, name="earthly_gourmet"),
    path("euclid_fish/", views.scrape_euclid_fish, name="euclid_fish"),
    path("farmart/", views.scrape_farmart, name="farmart"),
    path("get_fresh_produce/", views.scrape_get_fresh_produce, name="get_fresh_produce"),
    path("northeast_specialty/", views.scrape_northeast_specialty, name="northeast_specialty"),
    path("palmer_foods/", views.scrape_palmer_foods, name="palmer_foods"),
    path("perrone/", views.scrape_perrone, name="perrone"),
    path("seattle_fish/", views.scrape_seattle_fish, name="seattle_fish"),
    path("testa_produce/", views.scrape_testa_produce, name="testa_produce"),
    path("schenck_foods/", views.scrape_schenck_foods, name="schenck_foods"),
    path("express_foods/", views.scrape_express_foods, name="express_foods"),
    path("flanagan_foodservice/", views.scrape_flanagan_foodservice, name="flanagan_foodservice"),
    path('process-directory/', views.process_distributor_directory, name='process_distributor_directory'),
    path('add-column-to-csv/', views.add_column_to_csv, name='add_column_to_csv'),

]
