from django.urls import path
from . import views

from .views import (
    ScrapeProductsPageView,
    get_processing_progress,
    stop_processing,
    task_progress,
    stop_task,
    find_zero_skus,
    list_all_urls,
)
from .views import json_to_csv

# app_name = 'machine'
urlpatterns = [
    path("cooks_company/", views.scrape_cooks_company, name="cooks_company"),
    # path("sysco_api/", SyscoApiPageView.as_view(), name="sysco_api"),
    path("ab/", views.scrape_ab, name="ab"),
    path("acme_steak/", views.scrape_acme_steak, name="acme_steak"),
    path("all_fresh_seafood/", views.scrape_all_fresh_seafood, name="all_fresh_seafood"),
    path("alpeake/", views.scrape_alpeake, name="alpeake"),
    path("api/stop_processing/", stop_processing, name="stop_processing"),
    path("apito/", views.scrape_apito, name="apito"),
    path("birite/", views.scrape_birite, name="birite"),
    path("breakthru/", views.scrape_breakthru, name="breakthru"),
    path("carmela/", views.scrape_carmela, name="carmela"),
    path("caruso/", views.scrape_caruso, name="caruso"),
    path("cheese_importers/", views.scrape_cheese_importers, name="cheese_importers"),
    path("chefs_kitchen/", views.scrape_chefs_kitchen, name="chefs_kitchen"),
    path("cheney_brothers/", views.scrape_cheney_brothers, name="cheney_brothers"),
    path("citylinefoods/", views.scrape_citylinefoods, name="citylinefoods"),
    path("christ_panos/", views.scrape_christ_panos, name="christ_panos"),
    path("cooks_company/", views.scrape_cooks_company, name="cooks_company"),
    path("creamco/", views.scrape_creamco, name="creamco"),
    path("crookbros/", views.scrape_crookbros, name="crookbros"),
    path("cusumanoandsons/", views.scrape_cusumanoandsons, name="cusumanoandsons"),
    path("cw/", views.scrape_cw, name="cw"),
    path("derstines/", views.scrape_derstines, name="derstines"),
    path("driscoll/", views.scrape_driscoll, name="driscoll"),
    path("dwcspecialties/", views.scrape_dwcspecialties, name="dwcspecialties"),
    path("foodandpaper/", views.scrape_foodandpaper, name="foodandpaper"),
    path("foodpro/", views.scrape_foodpro, name="foodpro"),
    path("fourstarmeat/", views.scrape_fourstarmeat, name="fourstarmeat"),
    path("get_processing_progress/", get_processing_progress, name="get_processing_progress"),
    path("hooktofork/", views.scrape_hooktofork, name="hooktofork"),
    path("indianhead/", views.scrape_indianhead, name="indianhead"),
    path("jordanpaige/", views.scrape_jordanpaige, name="jordanpaige"),
    path("manson/", views.scrape_manson, name="manson"),
    path("maple_vale/", views.scrape_maple_vale, name="maple_vale"),
    path("market_406/", views.scrape_market_406, name="market_406"),
    path("misterproduce/", views.scrape_misterproduce, name="misterproduce"),
    path("pacificprovisions/", views.scrape_pacificprovisions, name="pacificprovisions"),
    path("prdeli/", views.scrape_prdeli, name="prdeli"),
    path("primesourcefoods/", views.scrape_primesourcefoods, name="primesourcefoods"),
    path("rarefoods/", views.scrape_rarefoods, name="rarefoods"),
    path("realityfoods/", views.scrape_realityfoods, name="realityfoods"),
    path("safradistribution/", views.scrape_safradistribution, name="safradistribution"),
    path("savalfoodservice/", views.scrape_savalfoodservice, name="savalfoodservice"),
    path("scrape_products/", ScrapeProductsPageView.as_view(), name="scrape_products"),
    path("scrapers/count-csv-rows/", views.count_csv_rows, name="count_csv_rows"),
    path("scrapers/search-requests/", views.search_requests, name="search_requests"),
    path("scrapers/update-distributor/", views.update_distributor, name="update_distributor"),
    path("sg/", views.scrape_sg, name="sg"),
    path("sierra_meat/", views.scrape_sierra_meat, name="sierra_meat"),
    path("socomeatco/", views.scrape_socomeatco, name="socomeatco"),
    path("southwest_traders/", views.scrape_southwest_traders, name="southwest_traders"),
    path("sunbelt/", views.scrape_sunbelt, name="sunbelt"),
    path("sutters/", views.scrape_sutters, name="sutters"),
    path("thefishguys/", views.scrape_thefishguys, name="thefishguys"),
    path("tolteca/", views.scrape_tolteca, name="tolteca"),
    path("totalfoods/", views.scrape_totalfoods, name="totalfoods"),
    path("usfoods/", views.scrape_usfoods, name="usfoods"),
    path("valleygold/", views.scrape_valleygold, name="valleygold"),
    path("vitco_foods/", views.scrape_vitco_foods, name="vitco_foods"),
    path("wagner/", views.scrape_wagner, name="wagner"),
    path("whatchefswant-south/", views.scrape_whatchefswant_south, name="whatchefswant_south"),
    path("whatchefswant_central/", views.scrape_whatchefswant_central, name="whatchefswant_central"),
    path("whatchefswant_rockies/", views.scrape_whatchefswant_rockies, name="whatchefswant_rockies"),
    path("woolcofoods/", views.scrape_woolcofoods, name="woolcofoods"),
    path("hearty/", views.scrape_hearty, name="hearty"),
    path("primizie_ny/", views.scrape_primizie_ny, name="primizie_ny"),
    path("primizie_noca/", views.scrape_primizie_noca, name="primizie_noca"),
    path("sandw/", views.scrape_sandw, name="sandw"),
    path("sardilli/", views.scrape_sardilli, name="sardilli"),
    path("status/", views.scraper_status, name="scraper_status"),
    path('task-status/', views.task_status, name='task_status'),
    path('stop-task/<str:task_id>/', views.stop_task, name='stop_task'),
    path('unipro/', views.scrape_unipro, name='unipro'),
    # Task progress and control endpoints
    path('api/task-progress/<str:task_id>/', task_progress, name='api_task_progress'),
    path('api/stop-task/<str:task_id>/', stop_task, name='api_stop_task'),

    path('json-to-csv/', json_to_csv, name='json_to_csv'),

    path('find-zero-skus/', find_zero_skus, name='find_zero_skus'),

    path('all-urls/', list_all_urls, name='all_urls'),

]
